# Generated by Django 3.1.2 on 2020-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.CharField(max_length=16, unique=True, verbose_name='Confirmation Number')),
                ('name', models.CharField(max_length=100, verbose_name='Last/Family Name')),
                ('birth', models.IntegerField(verbose_name='Year of Birth')),
            ],
        ),
    ]
