# Generated by Django 3.1.2 on 2020-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=16, unique=True, verbose_name='Case Number')),
                ('confirm_number', models.CharField(max_length=16, unique=True, verbose_name='Confirmation Number')),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('ATTORNEY', 'ATTORNEY'), ('THIRD', 'THIRD-PARTY-AGENT')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='puser',
            old_name='confirm',
            new_name='confirm_number',
        ),
    ]
