# Generated by Django 3.1.2 on 2020-10-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201022_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='birth_date',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
