# Generated by Django 3.1.2 on 2020-10-24 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201022_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puser',
            options={'verbose_name': 'Ariza topshirganlar'},
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'verbose_name': "Go'liblar"},
        ),
        migrations.AlterField(
            model_name='puser',
            name='birth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2010)], verbose_name='Year of Birth'),
        ),
    ]
