# Generated by Django 3.1.2 on 2020-10-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201024_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'verbose_name': "G'oliblar", 'verbose_name_plural': "G'oliblar"},
        ),
    ]
