# Generated by Django 3.1.2 on 2020-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201024_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
