# Generated by Django 3.1.2 on 2020-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_puser_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'SPOUSE'), ('CHILD', 'CHILD')], max_length=20)),
            ],
        ),
    ]
