# Generated by Django 3.1.2 on 2020-10-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.winner'),
        ),
    ]
