# Generated by Django 3.1.2 on 2020-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_member_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='winner',
        ),
        migrations.AddField(
            model_name='winner',
            name='winner',
            field=models.ManyToManyField(blank=True, to='app.Member'),
        ),
    ]
