# Generated by Django 3.1.2 on 2020-10-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201026_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='winner',
            name='lastname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='winner',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
