# Generated by Django 3.1.2 on 2020-10-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201026_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='winner',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
