# Generated by Django 3.1.2 on 2020-10-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201026_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
