# Generated by Django 3.1.2 on 2020-10-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201026_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='winner',
            new_name='member',
        ),
    ]
